#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1516688390                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
#playstore_link                            :                                          # Enter Google Play Store URL.
#presskit_download_link                    : https://tradingflowapp.github.io         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Simulate trade operations and calculate gains and losses

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jérôme Blanc
your_link                                 : https://tradingflowapp.github.io
#your_city                                 : Copenhagen
email_address                             : tradingflow@comuty.net
#facebook_username                         :
#instagram_username                        : ebaehr
#twitter_username                          : ebaehr
#github_username                           : tradingflow
#youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Simulate trade operations
    description                           : Create trade flows, make a deposit and simulate sells and buys operations. Withdraws or deposits can be added at any time, you can simulate complex scenarios with multiple financial instruments.
    fontawesome_icon_name                 : chart-line
 
  - title                                 : Estimate gains and losses
    description                           : Fees are taken into consideration for each buy or sell operation. Final gain or loss is automatically calculated.
    fontawesome_icon_name                 : calculator
 
  - title                                 : Use multiple financial instruments
    description                           : Large choice of financial instruments. A flow can help to simulate swaps between different financial instruments.
    fontawesome_icon_name                 : coins

  - title                                 : Customize financial instruments
    description                           : Did not found a financial instrument ? Just add it and use it. You can also customize each pre-defined financial instrument.
    fontawesome_icon_name                 : user-plus

  - title                                 : Updates
    description                           : More feature will come soon ...
    fontawesome_icon_name                 : calendar-check

#  - title                                 : Follow your wallet [coming soon]
#    description                           : bla bla bla ...
#    fontawesome_icon_name                 : wallet



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/trading.jpg                         # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"




####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

#Site map gen
plugins:
    - jekyll-sitemap
